### PR TITLE
remove print statement

### LINKED ISSUE #7: remove unnecessary print statement
This line is to be removed.

https://github.com/siruku6/oanda_accessor_pyv20/blob/c24b5191c41b52e6e7f6546874b13d475b8f1c98/oanda_accessor_pyv20/api.py#L120

### PR DESCRIPTION
**Pull request by DamyanBG**
I am merging my work related to #7

### CODE REVIEW

**Review by siruku6 — APPROVED** [review]

**Comment by siruku6** [comment]
@DamyanBG 
Thank you for fixing!

But, hmm..., I don't know why CI, Github Actions, doesn't work.
Do you have any idea to make CI work even if you make pull request from the repository you folked next time?

**Comment by DamyanBG** [comment]
On my repositories I have to give an approval before the CI to starts.

**Comment by siruku6** [comment]
Oh, I see. Thank you.
I should have asked and waited for you approve it 😢

**Comment by DamyanBG** [comment]
I mean that the owner have to approve - the owner of the repository.

**Comment by siruku6** [comment]
hmmm, I wonder how to do that🤔
I'll look in.

**Comment by siruku6** [comment]
I've found.
Exactly, [this document](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) tells us how to approve that.

But, though I'm not sure, there was not such button, "Approve and run"...
Maybe something in `.github/****.yml` is lacking for running CI for pull request from folks.

Anyway, thank you for your advice and information! @DamyanBG

**Comment by DamyanBG** [comment]
Take a closer look to your branch restrictions too.

**Pull request merged**
